networks:
  dmz:
    driver: bridge
    #driver: macvlan
    #driver_opts:
      #parent: eth0
    ipam:
      config:
        - subnet: "10.1.2.0/24"
          gateway: "10.1.2.1"


services:

  juice-shop:
    image: bkimminich/juice-shop
    build: 
      context: ./web1
      dockerfile: ./Dockerfile
    networks:
      dmz:
        ipv4_address: 10.1.2.2
    ports:
      - "4000:3000"


  nginx_publico:
    image: nginx:1.29.6-alpine-slim
    build: 
      context: ./web2
      dockerfile: ./Dockerfile
    networks:
      dmz:
        ipv4_address: 10.1.2.3
    ports:
      - "4001:80"

  ftpd_anonimo:
    image: instrumentisto/pure-ftpd:1.0.53
    build: 
      context: ./ftpd
      dockerfile: ./Dockerfile
    networks:
      dmz:
        ipv4_address: 10.1.2.4
    ports:
      - "4002:20"
      - "4003:21"
      - "30000-30009:30000-30009"
    environment:
      PUBLICHOST: "127.0.0.1"
      FTP_PASSIVE_PORTS: "30000:30009"
      ANONYMOUS_USER_ENABLED: "true"
      ANONYMOUS_UPLOAD_ENABLED: "true"
      ANONYMOUS_MKDIR_ENABLED: "true"
    volumes:
      - ftpdata:/var/ftp 


volumes:
  ftpdata:
