server {
    listen 80;
    listen [::]:80;

    server_name grupoa www.grupoa proxy.equipoa.local;

    location = /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }

    location / {
        proxy_pass http://10.1.2.2:8080;
        include /etc/nginx/proxy_params;
    }
}
