LDAPServer 10.2.3.5
LDAPPort 389
LDAPBaseDN dc=equipoa,dc=local
LDAPBindDN cn=Administrator,cn=Users,dc=equipoa,dc=local
LDAPBindPW ChangeMe-SambaAdmin-2026!
LDAPDefaultUID 1000
LDAPDefaultGID 1000
LDAPForceDefaultUID 1
LDAPForceDefaultGID 1
LDAPFilter (sAMAccountName=\L)
